# Delen en bewerken mag maar laat deze eerste regels staan.
# Bron : https://www.huizebruin.nl
# Bron File : https://github.com/huizebruin/s0tool/tree/main/esphome
# © Huizebruin.nl
substitutions:
  name: s0tool-watermeter
  wifi_ssid: 
  wifi_password:
  wifi_fast_connect: false
  wifi_fast_connect: false
  networks_use_address: "s0tool.local"
  networks_domain: ".local"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini
  name_add_mac_suffix: true
  esp8266_restore_from_flash: true
  comment: '${device_description}'
  project:
    name: "huizebruin.${name}"
    version: "${vdate}"

dashboard_import:
  package_import_url: github://huizebruin/s0tool/esphome/watermeter.yaml

packages:
  remote_package:
    url: https://github.com/huizebruin/s0tool/
    ref: main
    files:
      - esphome/components/basis.yaml
      - esphome/components/watermeter.yaml
    refresh: 0d
